pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        echo 'Starting Back-end stage...'
        sh 'mvn --version'
        echo 'Back-end stage completed.'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:17-alpine' }
      }
      steps {
        echo 'Starting Front-end stage...'
        sh 'node --version'
        echo 'Listing files before npm install...'
        sh 'ls -la'
        echo 'Running npm install...'
        sh 'npm install'
        echo 'Listing files after npm install...'
        sh 'ls -la'
        echo 'Front-end stage completed.'
      }
    }
  }
}
